[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_vs_eth = "AHX2zXNjyVNBWMyMUcpPtcxiuWG44ZzEmPdKe4z8KnSC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[[test.validator.clone]]
# pyth oracle program
address = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"

[[test.validator.clone]]
# sol/usd feed
address= "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"

[[test.validator.clone]]
# eth/usd feed
address = "JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB"


[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
